import fs from "node:fs/promises";
import path from "node:path";
import process from "node:process";

import PocketBase from "pocketbase";

const DEFAULT_OUTPUT_PATH = "src/types/pocketbase.ts";
const ENV_FILES = [".env.local.example", ".env", ".env.local"];
const BASE_RECORD_FIELDS = new Set(["id", "collectionId", "collectionName", "created", "updated"]);
const IDENTIFIER_PATTERN = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

async function main() {
  await loadEnvironmentFiles(process.cwd(), ENV_FILES);

  const pocketBaseUrl = getRequiredEnv(["NEXT_PUBLIC_PB_URL"]);
  const superuserEmail = getRequiredEnv(["PB_SUPERUSER_EMAIL"]);
  const superuserPassword = getRequiredEnv(["PB_SUPERUSER_PASSWORD"]);
  const includeSystemCollections = getBooleanEnv("PB_TYPEGEN_INCLUDE_SYSTEM", false);
  const outputPath = path.resolve(
    process.cwd(),
    process.env.PB_TYPEGEN_OUTPUT?.trim() || DEFAULT_OUTPUT_PATH
  );

  const pb = new PocketBase(pocketBaseUrl);
  pb.autoCancellation(false);

  await authenticateSuperuser(pb, superuserEmail, superuserPassword);

  const allCollections = await pb.collections.getFullList({
    sort: "name",
  });

  const collections = allCollections.filter(function filterCollections(collection) {
    return includeSystemCollections || !collection.system;
  });

  const output = renderPocketBaseTypesFile(collections);

  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.writeFile(outputPath, output, "utf8");

  const relativeOutputPath = path.relative(process.cwd(), outputPath) || outputPath;

  process.stdout.write(
    [
      "PocketBase typegen complete.",
      `Collections: ${collections.length}`,
      `Output: ${relativeOutputPath}`,
    ].join(" ") + "\n"
  );
}

async function loadEnvironmentFiles(rootDir, fileNames) {
  for (const fileName of fileNames) {
    const filePath = path.join(rootDir, fileName);

    let fileContent = "";

    try {
      fileContent = await fs.readFile(filePath, "utf8");
    } catch (error) {
      if (isFileNotFound(error)) {
        continue;
      }

      throw error;
    }

    const parsedValues = parseEnvFile(fileContent);

    for (const [key, value] of Object.entries(parsedValues)) {
      process.env[key] = value;
    }
  }
}

function parseEnvFile(content) {
  const env = {};
  const lines = content.split(/\r?\n/);

  for (const rawLine of lines) {
    const line = rawLine.trim();

    if (!line || line.startsWith("#")) {
      continue;
    }

    const match = line.match(/^(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/);

    if (!match) {
      continue;
    }

    const [, key, rawValue] = match;
    env[key] = parseEnvValue(rawValue);
  }

  return env;
}

function parseEnvValue(rawValue) {
  const value = rawValue.trim();

  if (!value) {
    return "";
  }

  if (value.startsWith('"') || value.startsWith("'")) {
    const quote = value[0];
    const closingQuoteIndex = findClosingQuoteIndex(value, quote);

    if (closingQuoteIndex === -1) {
      throw new Error(`Invalid quoted env value: ${rawValue}`);
    }

    const innerValue = value.slice(1, closingQuoteIndex);

    if (quote === '"') {
      return innerValue
        .replace(/\\n/g, "\n")
        .replace(/\\r/g, "\r")
        .replace(/\\t/g, "\t")
        .replace(/\\"/g, '"')
        .replace(/\\\\/g, "\\");
    }

    return innerValue;
  }

  return value.replace(/\s+#.*$/, "").trim();
}

function findClosingQuoteIndex(value, quote) {
  for (let index = 1; index < value.length; index += 1) {
    if (value[index] !== quote) {
      continue;
    }

    let backslashCount = 0;

    for (
      let escapeIndex = index - 1;
      escapeIndex >= 0 && value[escapeIndex] === "\\";
      escapeIndex -= 1
    ) {
      backslashCount += 1;
    }

    if (backslashCount % 2 === 0) {
      return index;
    }
  }

  return -1;
}

function getRequiredEnv(names) {
  for (const name of names) {
    const value = process.env[name]?.trim();

    if (value) {
      return value;
    }
  }

  throw new Error(`Missing required environment variable. Tried: ${names.join(", ")}`);
}

function getBooleanEnv(name, defaultValue) {
  const value = process.env[name]?.trim().toLowerCase();

  if (!value) {
    return defaultValue;
  }

  return value === "1" || value === "true" || value === "yes" || value === "on";
}

async function authenticateSuperuser(pb, email, password) {
  await pb.collection("_superusers").authWithPassword(email, password);
}

function renderPocketBaseTypesFile(collections) {
  const interfaceNamesByCollection = buildCollectionInterfaceNames(collections);
  const lines = [];

  lines.push("// This file is auto-generated by scripts/pocketbase-typegen.mjs.");
  lines.push("// Do not edit this file manually.");
  lines.push("");
  lines.push("export interface PocketBaseSystemFields {");
  lines.push("  id: string;");
  lines.push("  collectionId: string;");
  lines.push("  collectionName: string;");
  lines.push("  created: string;");
  lines.push("  updated: string;");
  lines.push("}");
  lines.push("");

  if (collections.length === 0) {
    lines.push("export interface PocketBaseCollections {}");
    lines.push("");
    lines.push("export type PocketBaseCollectionName = never;");
    lines.push("export type PocketBaseCollectionRecord<TName extends string> = never;");
    lines.push("");

    return `${lines.join("\n")}\n`;
  }

  for (const collection of collections) {
    const interfaceName = interfaceNamesByCollection.get(collection.name);

    if (!interfaceName) {
      continue;
    }

    lines.push(`export interface ${interfaceName} extends PocketBaseSystemFields {`);

    for (const field of collection.fields) {
      if (!field || typeof field.name !== "string") {
        continue;
      }

      if (BASE_RECORD_FIELDS.has(field.name)) {
        continue;
      }

      const optionalMarker = field.required && !field.hidden ? "" : "?";
      const propertyName = renderPropertyName(field.name);
      const fieldType = renderFieldType(field);

      lines.push(`  ${propertyName}${optionalMarker}: ${fieldType};`);
    }

    lines.push("}");
    lines.push("");
  }

  lines.push("export interface PocketBaseCollections {");

  for (const collection of collections) {
    const interfaceName = interfaceNamesByCollection.get(collection.name);

    if (!interfaceName) {
      continue;
    }

    lines.push(`  ${renderPropertyName(collection.name)}: ${interfaceName};`);
  }

  lines.push("}");
  lines.push("");
  lines.push("export type PocketBaseCollectionName = keyof PocketBaseCollections;");
  lines.push("export type PocketBaseCollectionRecord<TName extends PocketBaseCollectionName> =");
  lines.push("  PocketBaseCollections[TName];");
  lines.push("");

  return `${lines.join("\n")}\n`;
}

function buildCollectionInterfaceNames(collections) {
  const result = new Map();
  const usedNames = new Set();

  for (const collection of collections) {
    const baseName = `${toPascalCase(collection.name)}Record`;
    let interfaceName = baseName;
    let suffix = 2;

    while (usedNames.has(interfaceName)) {
      interfaceName = `${baseName}${suffix}`;
      suffix += 1;
    }

    usedNames.add(interfaceName);
    result.set(collection.name, interfaceName);
  }

  return result;
}

function toPascalCase(value) {
  const parts = value.split(/[^A-Za-z0-9]+/).filter(Boolean);
  const raw = parts
    .map(function mapPart(part) {
      return part.charAt(0).toUpperCase() + part.slice(1);
    })
    .join("");

  if (!raw) {
    return "Collection";
  }

  if (/^[0-9]/.test(raw)) {
    return `Collection${raw}`;
  }

  return raw;
}

function renderPropertyName(name) {
  if (IDENTIFIER_PATTERN.test(name)) {
    return name;
  }

  return JSON.stringify(name);
}

function renderFieldType(field) {
  const isMultiple = isMultiValueField(field);
  const singleType = renderSingleFieldType(field);

  if (!isMultiple) {
    return singleType;
  }

  if (singleType.includes(" | ")) {
    return `Array<${singleType}>`;
  }

  return `${singleType}[]`;
}

function isMultiValueField(field) {
  if (!field || typeof field !== "object") {
    return false;
  }

  if (!["relation", "file", "select"].includes(field.type)) {
    return false;
  }

  if (typeof field.maxSelect !== "number") {
    return false;
  }

  return field.maxSelect !== 1;
}

function renderSingleFieldType(field) {
  switch (field.type) {
    case "bool":
      return "boolean";
    case "number":
    case "autonumber":
      return "number";
    case "json":
      return "unknown";
    case "relation":
      return "string";
    case "select":
      return renderSelectFieldType(field);
    case "file":
      return "string";
    case "date":
    case "autodate":
      return "string";
    case "text":
    case "editor":
    case "email":
    case "url":
    case "phone":
    case "password":
      return "string";
    case "user":
      return "string";
    default:
      return "unknown";
  }
}

function renderSelectFieldType(field) {
  if (!Array.isArray(field.values)) {
    return "string";
  }

  const values = field.values
    .filter(function filterValue(value) {
      return typeof value === "string";
    })
    .map(function mapValue(value) {
      return JSON.stringify(value);
    });

  if (values.length === 0) {
    return "string";
  }

  return Array.from(new Set(values)).join(" | ");
}

function isFileNotFound(error) {
  return Boolean(error) && typeof error === "object" && error.code === "ENOENT";
}

main().catch(function handleError(error) {
  const message = error instanceof Error ? error.message : String(error);

  console.error(`PocketBase typegen failed: ${message}`);
  const clientErrorDetails = formatClientErrorDetails(error);

  if (clientErrorDetails) {
    console.error(clientErrorDetails);
  }

  if (error instanceof Error && error.stack) {
    console.error(error.stack);
  }

  process.exitCode = 1;
});

function formatClientErrorDetails(error) {
  if (!error || typeof error !== "object") {
    return "";
  }

  const status = typeof error.status === "number" ? error.status : null;
  const url = typeof error.url === "string" ? error.url : null;
  const response = error.response && typeof error.response === "object" ? error.response : null;

  const detailLines = [];

  if (status !== null) {
    detailLines.push(`status=${status}`);
  }

  if (url) {
    detailLines.push(`url=${url}`);
  }

  if (response && Object.keys(response).length > 0) {
    try {
      detailLines.push(`response=${JSON.stringify(response)}`);
    } catch {
      detailLines.push("response=[unserializable]");
    }
  }

  return detailLines.join(" ");
}
